export const SIMPLE_DATABASE_UPDATE_USERS = "SIMPLE_DATABASE_UPDATE_USERS";
export const SIMPLE_DATABASE_RESPONSE_STATUS = "SIMPLE_DATABASE_RESPONSE_STATUS";
export const USER_STATUS = "USER_STATUS";
export const ACTIVE_ARTICLE = "ACTIVE_ARTICLE";
export const SIDEBAR_LINKS = "SIDEBAR_LINKS";
