s/--MAIN-TEXT-COLOR--/black/g;
s/--MAIN-BACKGROUND-COLOR--/#f5f5f5/g;
s/--MAIN-LINK-BACKGROUND-COLOR--/blue/g;
s/--MAIN-LINK-HOVER-BACKGROUND-COLOR--/gray/g;
s/--MAIN-LINK-HOVER-TEXT-COLOR--/white/g;
s/--MAIN-LINK-TEXT-COLOR--/black/g;
s/--MAIN-BORDER-COLOR--/black/g;
s/--NAV-LINK-TEXT-COLOR--/black/g;
s/--NAV-LINK-BACKGROUND-COLOR--/white/g;
s/--NAV-LINK-HOVER-TEXT-COLOR--/black/g;
s/--NAV-LINK-HOVER-BACKGROUND-COLOR--/#d8d8d8/g;
s/--STUB-BACKGROUND-COLOR--/#b9b9b9/g;
s/--STUB-H3-COLOR--/#949494/g;
s/--ARTICLE-HEADER-TEXT-COLOR--/teal/g;
s/--CODE-FILENAME--/#ff00ff/g;
s/--CODE-SOURCE--/#9f99ff/g;
s/--CODE-COMMAND--/#0fa10f/g;
s/--CODE-BOX-COLOR--/#424242/g;
s/--CODE-BOX-WIDTH--/82ch/g;
s/--CODE-TEXT-FONT--/Monaco, MonoSpace/g;
s/--MAIN-TEXT-SIZE--/14px/g;
s/--MAIN-TEXT-FONT--/"Lucida Grande", Helvetica, Arial, sans-serif/g;
