s/-MAIN-TEXT-COLOR-/black/;
s/-BACKGROUND-COLOR-/white/;
s/-LINK-BACKGROUND-COLOR-/blue/;
s/-LINK-HOVER-BACKGROUND-COLOR-/gray/;
s/-LINK-TEXT-COLOR-/red/;
s/-ARTICLE-STUB-BACKGROUND-COLOR-/pink/;
s/-ARTICLE-STUB-H3-COLOR/orange/;

