//USER ACTION CONSTANTS
export const UPDATE_USER_LIST = "UPDATE_USER_LIST";
export const USER_STATUS = "USER_STATUS";
export const SET_ACTIVE_USER = "SET_ACTIVE_USER";

//ARTICLE ACTION CONSTANTS
export const ACTIVE_ARTICLE = "ACTIVE_ARTICLE";
export const ALL_ARTICLES = "ALL_ARTICLES";

//TITLE ACTION CONSTANTS
export const BLOG_TITLES = "BLOG_TITLES";
export const PROJECT_TITLES = "PROJECT_TITLES";

//NAV ACTIONS
export const PARENT_TOPIC = "PARENT_TOPIC";

//CALLBACKS
export const EDIT_ARTICLE_CB = "EDIT_ARTICLE_CB";

//HOME ACTION CONSTANTS
export const SET_HOME = "SET_HOME";
