//USER ACTION CONSTANTS
export const UPDATE_USER_LIST = "UPDATE_USER_LIST";
export const USER_STATUS = "USER_STATUS";
export const SET_ACTIVE_USER = "SET_ACTIVE_USER";

//ARTICLE ACTION CONSTANTS
export const ACTIVE_ARTICLE = "ACTIVE_ARTICLE";
export const ALL_ARTICLES = "ALL_ARTICLES";
export const ALL_ARTICLES_TITLES = "ALL_ARTICLES_TITLES";

//HOME ACTION CONSTANTS
export const SET_HOME = "SET_HOME";
